import { createSlice } from "@reduxjs/toolkit";

const initialState = {
    searchQuery: "",
};

export const findSlice = createSlice({
    name: "findSlice",
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        doGetSearchQuery: (state, action) => {
            // Redux Toolkit allows us to write "mutating" logic in reducers. It
            // doesn't actually mutate the state because it uses the Immer library,
            // which detects changes to a "draft state" and produces a brand new
            // immutable state based off those changes

            state.searchQuery = action.payload;
        },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
});

export const selectIsAuthenticated = (state) => state.findSlice.isAuthenticated;

export const { doGetSearchQuery } = findSlice.actions;

export default findSlice.reducer;
