import { createSlice } from "@reduxjs/toolkit";

const initialState = {
    isAuthenticated: false,
    isLoading: true,
    isLoginWithGoogle: false,
    user: {
        email: "",
        phone: "",
        name: "",
        role: "",
        id: "",
    },
};

export const accountSlide = createSlice({
    name: "accountSlide",
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        doLoginAction: (state, action) => {
            // Redux Toolkit allows us to write "mutating" logic in reducers. It
            // doesn't actually mutate the state because it uses the Immer library,
            // which detects changes to a "draft state" and produces a brand new
            // immutable state based off those changes
            state.isAuthenticated = true;
            state.isLoading = false;
            state.user = action.payload;
        },
        doLoginWithGoogle: (state) => {
            // Redux Toolkit allows us to write "mutating" logic in reducers. It
            // doesn't actually mutate the state because it uses the Immer library,
            // which detects changes to a "draft state" and produces a brand new
            // immutable state based off those changes
            state.isLoginWithGoogle = true;
        },

        doLogoutAction: (state) => {
            localStorage.removeItem("access_token");
            state.isAuthenticated = false;
            state.isLoginWithGoogle = false;
            state.user = {
                email: "",
                phone: "",
                name: "",
                role: "",
                id: "",
            };
        },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
});

export const selectIsAuthenticated = (state) =>
    state.accountSlide.isAuthenticated;

export const { doLoginAction, doLoginWithGoogle, doLogoutAction } =
    accountSlide.actions;

export default accountSlide.reducer;
